### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by llacqie** [finogeeks/Ligase#91]
When compiling on ubuntu 20.04 got:
github.com/finogeeks/ligase/syncserver/consumers
../../syncserver/consumers/push.go:199:4: too many arguments in call to func literal
	have (string, *gomatrixserverlib.ClientEvent, string, int, int64, int64, *[]byte, *pushapitypes.PushPubContents, bool)
	want (string, *gomatrixserverlib.ClientEvent, string, int, int64, int64, *[]byte, *pushapitypes.PushPubContents)

**Comment by GenTang** [comment]
@turnip-jing , Please check this bug.

**Comment by GenTang** [comment]
> When compiling on ubuntu 20.04 got:
> github.com/finogeeks/ligase/syncserver/consumers
> ../../syncserver/consumers/push.go:199:4: too many arguments in call to func literal
> have (string, *gomatrixserverlib.ClientEvent, string, int, int64, int64, *[]byte, *pushapitypes.PushPubContents, bool)
> want (string, *gomatrixserverlib.ClientEvent, string, int, int64, int64, *[]byte, *pushapitypes.PushPubContents)

Hi, which branch do you use? Thx

**Comment by llacqie** [comment]
Develop branch
